/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/Auth'
import { Route as AuthMethodsRouteImport } from './routes/AuthMethods'
import { Route as EmailAuthRouteImport } from './routes/EmailAuth'
import { Route as WelcomeRouteImport } from './routes/Welcome'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClassRouteImport } from './routes/class'
import { Route as ClassworkRouteImport } from './routes/classwork'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CreateRouteImport } from './routes/create'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FolderRouteImport } from './routes/folder'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LiveClassRouteImport } from './routes/live-class'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WhiteboardRouteImport } from './routes/whiteboard'
import { Route as FilesFolderIdRouteImport } from './routes/files_.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/Auth',
  path: '/Auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMethodsRoute = AuthMethodsRouteImport.update({
  id: '/AuthMethods',
  path: '/AuthMethods',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAuthRoute = EmailAuthRouteImport.update({
  id: '/EmailAuth',
  path: '/EmailAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/Welcome',
  path: '/Welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRoute = ClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassworkRoute = ClassworkRouteImport.update({
  id: '/classwork',
  path: '/classwork',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderRoute = FolderRouteImport.update({
  id: '/folder',
  path: '/folder',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassRoute = LiveClassRouteImport.update({
  id: '/live-class',
  path: '/live-class',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardRoute = WhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesFolderIdRoute = FilesFolderIdRouteImport.update({
  id: '/files_/$folderId',
  path: '/files/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Auth': typeof AuthRoute
  '/AuthMethods': typeof AuthMethodsRoute
  '/EmailAuth': typeof EmailAuthRoute
  '/Welcome': typeof WelcomeRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/assignments': typeof AssignmentsRoute
  '/chat': typeof ChatRoute
  '/class': typeof ClassRoute
  '/classwork': typeof ClassworkRoute
  '/courses': typeof CoursesRoute
  '/create': typeof CreateRoute
  '/files': typeof FilesRoute
  '/folder': typeof FolderRoute
  '/join': typeof JoinRoute
  '/live-class': typeof LiveClassRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/whiteboard': typeof WhiteboardRoute
  '/files/$folderId': typeof FilesFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Auth': typeof AuthRoute
  '/AuthMethods': typeof AuthMethodsRoute
  '/EmailAuth': typeof EmailAuthRoute
  '/Welcome': typeof WelcomeRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/assignments': typeof AssignmentsRoute
  '/chat': typeof ChatRoute
  '/class': typeof ClassRoute
  '/classwork': typeof ClassworkRoute
  '/courses': typeof CoursesRoute
  '/create': typeof CreateRoute
  '/files': typeof FilesRoute
  '/folder': typeof FolderRoute
  '/join': typeof JoinRoute
  '/live-class': typeof LiveClassRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/whiteboard': typeof WhiteboardRoute
  '/files/$folderId': typeof FilesFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Auth': typeof AuthRoute
  '/AuthMethods': typeof AuthMethodsRoute
  '/EmailAuth': typeof EmailAuthRoute
  '/Welcome': typeof WelcomeRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/assignments': typeof AssignmentsRoute
  '/chat': typeof ChatRoute
  '/class': typeof ClassRoute
  '/classwork': typeof ClassworkRoute
  '/courses': typeof CoursesRoute
  '/create': typeof CreateRoute
  '/files': typeof FilesRoute
  '/folder': typeof FolderRoute
  '/join': typeof JoinRoute
  '/live-class': typeof LiveClassRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/whiteboard': typeof WhiteboardRoute
  '/files_/$folderId': typeof FilesFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Auth'
    | '/AuthMethods'
    | '/EmailAuth'
    | '/Welcome'
    | '/announcements'
    | '/assessments'
    | '/assignments'
    | '/chat'
    | '/class'
    | '/classwork'
    | '/courses'
    | '/create'
    | '/files'
    | '/folder'
    | '/join'
    | '/live-class'
    | '/onboarding'
    | '/profile'
    | '/whiteboard'
    | '/files/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Auth'
    | '/AuthMethods'
    | '/EmailAuth'
    | '/Welcome'
    | '/announcements'
    | '/assessments'
    | '/assignments'
    | '/chat'
    | '/class'
    | '/classwork'
    | '/courses'
    | '/create'
    | '/files'
    | '/folder'
    | '/join'
    | '/live-class'
    | '/onboarding'
    | '/profile'
    | '/whiteboard'
    | '/files/$folderId'
  id:
    | '__root__'
    | '/'
    | '/Auth'
    | '/AuthMethods'
    | '/EmailAuth'
    | '/Welcome'
    | '/announcements'
    | '/assessments'
    | '/assignments'
    | '/chat'
    | '/class'
    | '/classwork'
    | '/courses'
    | '/create'
    | '/files'
    | '/folder'
    | '/join'
    | '/live-class'
    | '/onboarding'
    | '/profile'
    | '/whiteboard'
    | '/files_/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthMethodsRoute: typeof AuthMethodsRoute
  EmailAuthRoute: typeof EmailAuthRoute
  WelcomeRoute: typeof WelcomeRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ChatRoute: typeof ChatRoute
  ClassRoute: typeof ClassRoute
  ClassworkRoute: typeof ClassworkRoute
  CoursesRoute: typeof CoursesRoute
  CreateRoute: typeof CreateRoute
  FilesRoute: typeof FilesRoute
  FolderRoute: typeof FolderRoute
  JoinRoute: typeof JoinRoute
  LiveClassRoute: typeof LiveClassRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  WhiteboardRoute: typeof WhiteboardRoute
  FilesFolderIdRoute: typeof FilesFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth': {
      id: '/Auth'
      path: '/Auth'
      fullPath: '/Auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AuthMethods': {
      id: '/AuthMethods'
      path: '/AuthMethods'
      fullPath: '/AuthMethods'
      preLoaderRoute: typeof AuthMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EmailAuth': {
      id: '/EmailAuth'
      path: '/EmailAuth'
      fullPath: '/EmailAuth'
      preLoaderRoute: typeof EmailAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Welcome': {
      id: '/Welcome'
      path: '/Welcome'
      fullPath: '/Welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class': {
      id: '/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classwork': {
      id: '/classwork'
      path: '/classwork'
      fullPath: '/classwork'
      preLoaderRoute: typeof ClassworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder': {
      id: '/folder'
      path: '/folder'
      fullPath: '/folder'
      preLoaderRoute: typeof FolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class': {
      id: '/live-class'
      path: '/live-class'
      fullPath: '/live-class'
      preLoaderRoute: typeof LiveClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files_/$folderId': {
      id: '/files_/$folderId'
      path: '/files/$folderId'
      fullPath: '/files/$folderId'
      preLoaderRoute: typeof FilesFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthMethodsRoute: AuthMethodsRoute,
  EmailAuthRoute: EmailAuthRoute,
  WelcomeRoute: WelcomeRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssessmentsRoute: AssessmentsRoute,
  AssignmentsRoute: AssignmentsRoute,
  ChatRoute: ChatRoute,
  ClassRoute: ClassRoute,
  ClassworkRoute: ClassworkRoute,
  CoursesRoute: CoursesRoute,
  CreateRoute: CreateRoute,
  FilesRoute: FilesRoute,
  FolderRoute: FolderRoute,
  JoinRoute: JoinRoute,
  LiveClassRoute: LiveClassRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  WhiteboardRoute: WhiteboardRoute,
  FilesFolderIdRoute: FilesFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
